# Generated by Django 4.2.3 on 2023-07-04 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=2, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Неверный формат номера телефона.', regex='\\b\\+?[7,8](\\s*\\d{3}\\s*\\d{3}\\s*\\d{2}\\s*\\d{2})\\b')], verbose_name='Телефон'),
        ),
    ]
