# Generated by Django 4.2.3 on 2023-07-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Аккаунт с данной электронной почтой уже существует.'}, max_length=254, unique=True, verbose_name='Эл. почта'),
        ),
    ]
