# Generated by Django 4.2.3 on 2023-07-04 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Убедитесь, что поле имени содержит не менее 2 символов.')], verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Убедитесь, что поле фамилии содержит не менее 2 символов.')], verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=25, validators=[django.core.validators.EmailValidator(message='Введите корректный адрес электронной почты.')], verbose_name='Эл. почта')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('service_category', models.CharField(choices=[('DF', 'Выберите категорию услуги'), ('RC', 'Звукозапись'), ('MS', 'Мастеринг'), ('MX', 'Сведение'), ('GW', 'Написание текста')], default='DF', max_length=2, verbose_name='Категория')),
                ('feedback', models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=5, message='Убедитесь, что поле с отзывом содержит не менее 5 символов.')], verbose_name='Отзыв')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Оценка')),
            ],
        ),
    ]
