# Generated by Django 4.2.3 on 2023-07-04 12:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Убедитесь, что поле имени содержит не менее 2 символов.')], verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Убедитесь, что поле фамилии содержит не менее 2 символов.')], verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=25, validators=[django.core.validators.EmailValidator(message='Введите корректный адрес электронной почты.')], verbose_name='Эл. почта')),
                ('phone', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Неверный формат номера телефона.', regex='\\b\\+?[7,8](\\s*\\d{3}\\s*\\d{3}\\s*\\d{2}\\s*\\d{2})\\b')], verbose_name='Телефон')),
                ('date', models.DateField(null=True, verbose_name='Дата записи')),
                ('service_category', models.CharField(choices=[('DF', 'Выберите категорию услуги'), ('RC', 'Звукозапись'), ('MS', 'Мастеринг'), ('MX', 'Сведение'), ('GW', 'Написание текста')], default='DF', max_length=2, verbose_name='Категория')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=15, message='Убедитесь, что поле с сообщением содержит не менее 15 символов.')], verbose_name='Сообщение к заявке')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время записи')),
                ('sent_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения заявки')),
                ('accepted', models.BooleanField(default=False, verbose_name='Принята')),
                ('accepted_date', models.DateField(blank=True, null=True, verbose_name='Дата принятия заявки')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Потверждена')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.DateTimeField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.appointment')),
            ],
        ),
    ]
